"""create_subscriptions_table

Revision ID: 27abfb355e8e
Revises: 
Create Date: 2026-10-07 01:34:11.969648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27abfb355e8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reminder_days_before', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_cycle IN ('monthly', 'yearly', 'quarterly', 'weekly')", name='ck_subscription_billing_cycle'),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'archived', 'paused')", name='ck_subscription_status'),
    sa.CheckConstraint('price >= 0', name='ck_subscription_positive_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_renewal_date', 'subscriptions', ['renewal_date'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_renewal_date', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
